# -*- coding: utf-8 -*-
"""ReportProducer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c-g_oAk1uIVQxouC183no6s3ZOlzvZbD
"""

from pylatex import Document, Section, Tabular, Math, TikZ, Axis, \
    Plot, Figure, Matrix, Alignat, MultiRow, MultiColumn, Command, LongTable
from pylatex.utils import italic, NoEscape, bold


def createReport(featuresToBlame, predictions):
  doc = Document('Report')
  doc.preamble.append(Command('title', 'REPORT- EVALUATE CONCEPT DRIFT'))
  doc.preamble.append(Command('author', 'Yahel Jacobs and Gilad Daube'))
  doc.preamble.append(Command('date', 'Tabular Data Science course, BIU, Semester A, 2022'))
  doc.append(NoEscape(r'\maketitle'))
  doc.append(NoEscape(r'\renewcommand{\arraystretch}{1.2}'))

  doc.append('This is an automatic report to evaluate Concept drift. It divided into two sections: Features to blame and Future Distributions.')

  with doc.create(Section('Features to Blame')):
      doc.append(f'We detected {len(featuresToBlame)} features with different distribution after the drift. The blamed features and their old & new distributions are in the following table:')
      doc.append(Command('linebreak'))
  
  doc.append(NoEscape(r'\begin{center}'))
  
  with doc.create(LongTable('p{0.3\\textwidth}|p{0.3\\textwidth}|p{0.3\\textwidth}')) as table:
    table.add_row((MultiRow(2, data=NoEscape('Feature')), MultiColumn(2, data='Distribution'),))
    table.add_hline(2,3)
    table.add_row(('', 'Before', 'After'))
    for feature_name in featuresToBlame:
      distributionBefore = featuresToBlame.get(feature_name)[0]
      distributionAfter = featuresToBlame.get(feature_name)[1]
      table.add_hline()
      table.add_row((feature_name, distributionBefore, distributionAfter))
  
  doc.append(NoEscape(r'\end{center}'))
  doc.append(Command('linebreak'))

  with doc.create(Section('Future Distributions')):
    doc.append(f'We predict distribution for every feature, here are the results:')
    doc.append(Command('linebreak'))
  
  doc.append(NoEscape(r'\begin{center}'))
  
  with doc.create(LongTable('p{0.3\\textwidth}|p{0.3\\textwidth}')) as table:
    table.add_row(('Feature', 'Predict Distribution'))
    for feature_name in predictions:
      distribution = predictions.get(feature_name)
      table.add_hline()
      table.add_row((feature_name, distribution))
  doc.append(NoEscape(r'\end{center}'))
  doc.generate_pdf('report', clean_tex=False)